---
- hosts: localhost
  collections:
    - community.general
  connection: local
  gather_facts: False
  roles:
    - role: homebrew
      tags: homebrew
    - role: pipx
      tags: pipx
    - role: npm
      tags: npm
